sudo: false
language: python
python:
  - "3.5"

env:
  - JEKYLL_ENV=production

before_install:
  - rvm use 2.2.3 --install --fuzzy

install:
 - gem install --no-document jekyll
 - gem install jekyll-scholar
 - gem install unicode

script:
 - make deploy
